### ISSUE TITLE
This is on 1.20.1, EMI Error

### ISSUE THREAD

**Issue by lSherozl** [brnbrd/Delightful#92]
Aether Redux, Oh the Biomes we have gone, Farmers Delight and this mod together will lead to a critical EMI error. Keep all mods on latest versions. Just some small snippets from the log. The rest wont help you: 

[01Aug2024 03:52:57.519] [Thread-274/INFO] [EMI/]: [EMI] Loading plugin from emi
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: IRecipe#getRemainingItems was called with an inventory that does not match the recipe
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: according to IRecipe#matches. This is probably a bug in some mod in the following stacktrace,
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: if in doubt report it to Immersive Engineering
java.lang.IllegalArgumentException: null
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.getRemainingItems(AbstractFluidAwareRecipe.java:100) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23842!/:?]
	at blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.m_7457_(AbstractFluidAwareRecipe.java:27) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%23842!/:?]
	at dev.emi.emi.recipe.EmiShapedRecipe.setRemainders(EmiShapedRecipe.java:43) ~[emi-1.1.2+1.20.1+forge.jar%23775!/:?]
	at dev.emi.emi.VanillaPlugin.register(VanillaPlugin.java:419) ~[emi-1.1.2+1.20.1+forge.jar%23775!/:?]
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:183) ~[emi-1.1.2+1.20.1+forge.jar%23775!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: IRecipe#getRemainingItems was called with an inventory that does not match the recipe
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: according to IRecipe#matches. This is probably a bug in some mod in the following stacktrace,
[01Aug2024 03:52:57.704] [Thread-274/ERROR] [immersiveengineering/]: if in doubt report it to Immersive Engineering
java.lang.IllegalArgumentException: null

[01Aug2024 03:53:06.285] [Thread-274/INFO] [EMI/]: [EMI] Baking search
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] Critical error occured during reload:
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] java.lang.NoSuchMethodError: 'byte net.zepalesque.redux.item.util.VeridiumItem.getInfusion(net.minecraft.world.item.ItemStack)'
	at TRANSFORMER
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] delightful@3.5.5
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] net.brnbrd.delightful.common.item.knife.compat.aether_redux.VeridiumKnifeItem.m_7373_(VeridiumKnifeItem.java:51)
	at TRANSFORMER
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] minecraft@1.20.1
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631)
	at TRANSFORMER
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] dev.emi.emi.api.stack.ItemEmiStack.getTooltipText(ItemEmiStack.java:140)
	at TRANSFORMER
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] dev.emi.emi.search.EmiSearch.bake(EmiSearch.java:59)
	at TRANSFORMER
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] emi@1.1.2+1.20.1+forge
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:220)
	at java.base
[01Aug2024 03:53:07.017] [Thread-274/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Thread.java:833)

**Comment by lSherozl** [comment]
The above was tested on the Prominence 2 classic modpack on forge

**Comment by lSherozl** [comment]
https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/issues/30

**Comment by brnbrd** [comment]
This is using an outdated version of Delightful (3.5.5). The incompatibility with Aether Redux is fixed already.
